name: Actions 😎
on:
  pull_request: {}
  push: { branches: [master] }

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: WebGL
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
      
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: testing transportes server ssh connection  
        uses: appleboy/ssh-action@master
        with:
          host: 23.20.191.248
          username: root
          key: ${{secrets.KEY_SECRET}}
          port: 22
          script: |
            sudo su
            cp build/WebGL /home/admin/web/joder.enrique-dev.com/public_html/
          

  requestManualActivationFile:
    name: Request manual activation file 🔑
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2020.3.20f1
          # - 2020.1.0a15
    steps:
      # Checkout repository (required to test local actions)
      - name: Checkout repository
        uses: actions/checkout@v2

      # Request manual activation file
      - name: Request manual activation file
        id: getManualLicenseFile
        uses: ./
        with:
          unityVersion: ${{ matrix.unityVersion }}

      # Upload artifact (Unity_v20XX.X.XXXX.alf)
      - name: Expose as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.getManualLicenseFile.outputs.filePath }}
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
